export const ADD = 'todos/add'
export const DELETE = 'todos/delete'
export const TOGGLE = 'todos/toggle'
export const COLOR = 'todos/color'
export const COMPLETE_ALL = 'todos/completeAll'
export const CLEAR_COMPLETED = 'todos/clearCompleted'